### ISSUE TITLE
Processing Data Captured with on 2 tx and 4rx

### ISSUE THREAD

**Issue by Lynnes001** [PreSenseRadar/OpenRadar#15]
Thanks for the opensource library!

I am using AWR1642 ods, which has 2tx and 4rx. In angle_estimation.naive_xyz, it says "need a config for more than 2 TXs". 
I'd like to know does the visualizing programs are built specifically for 3tx radar?

Thanks

**Comment by edwin-pan** [comment]
Yes that function is built specifically for radar's with more than 2 tx antennas. We used the TI IWR1843 to test the naive_xyz functionality. For 2tx antennas, range-azimuth should be sufficient.

**Comment by Lynnes001** [comment]
Thanks for clarifying.

Yeah because I saw there are config and files named awr1642. So I’d like to find out.

On Mar 18, 2020, at 5:49 PM, Edwin Pan <notifications@github.com> wrote:

﻿

Yes that function is built specifically for radar's with more than 2 tx antennas. We used the TI IWR1843 to test the naive_xyz functionality. For 2tx antennas, range-azimuth should be sufficient.
