### ISSUE TITLE
Visualizing micro doppler plots

### ISSUE THREAD

**Issue by bayramf** [PreSenseRadar/OpenRadar#18]
### Discussion about plotting of micro doppler signatures, as they have an enormous importance in the field of machine learning.
This issue is a follow-up to #17.

**Comment by bayramf** [comment]
Hi @edwin-pan ,

I already took a look at your project work "FMCW Radar-based Human Movement Classification from uDoppler signatures". Nice results! How you did you generate these spectograms (see below)? Are these simulated data or did you convert range doppler maps captured with mmwave radar to these figures? If I use your scratchbook.py or generate_spectrum_from_RDC.py I can't get anywhere near your results.

Thanks in advance!

![Unbenannt](https://user-images.githubusercontent.com/62951045/80275587-9a704000-86e2-11ea-96e2-e138ed119a20.PNG)

**Comment by edwin-pan** [comment]
Hi @bayramf ,

These are simulated plots taken from Matlab's Phased Array Toolbox Demo ([link](https://www.mathworks.com/help/deeplearning/ug/pedestrian-and-bicyclist-classification-using-deep-learning.html)). The results from the TI radar won't be as clean. However, I think you can still generate data with learnable features using the TI platform + processing like the scratchbook.py script.
