### ISSUE TITLE
data cannot download

### ISSUE THREAD

**Issue by wangshuxuan123** [PreSenseRadar/OpenRadar#37]
Hello, the data download link you provided seems to be invalid. Is there a new download link?

**Comment by edwin-pan** [comment]
Which data download link are you referring to? I just tried downloading `circle.bin` and it went through without a hitch.

**Comment by tzzydh** [comment]
HELLO, this link  "https://docs.google.com/uc?export=download" can't open ,

**Comment by xiayh1992** [comment]
> HELLO, this link "https://docs.google.com/uc?export=download" can't open ,
download data by excuting download.py in demo file.

**Comment by edwin-pan** [comment]
Yes. Please use the provided [download_data.py](https://github.com/PreSenseRadar/OpenRadar/blob/master/demo/people_tracking/download_data.py) script to download the demo data.

**Comment by yjhuasheng** [comment]
> Yes. Please use the provided [download_data.py](https://github.com/PreSenseRadar/OpenRadar/blob/master/demo/people_tracking/download_data.py) script to download the demo data.

can you send the "circle.bin" to me？Thank you very much

**Comment by yjhuasheng** [comment]
> Yes. Please use the provided [download_data.py](https://github.com/PreSenseRadar/OpenRadar/blob/master/demo/people_tracking/download_data.py) script to download the demo data.

Could you send the data to me? thanks

**Comment by yjhuasheng** [comment]
> Could you send the data to me? thanks

Could you send the data to me? thanks

**Comment by xiayh1992** [comment]
你好，你自己运行Python下载脚本就可以下载数据和允许代码了。



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 1, 2024 17:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PreSenseRadar/OpenRadar] data cannot download (#37)




  
Could you send the data to me? thanks
  
Could you send the data to me? thanks
