### ISSUE TITLE
invalid arguments to method call

### ISSUE THREAD

**Issue by TajVeerThiara** [PreSenseRadar/OpenRadar#8]
I tried running the 1843_mmwavestudio_config.lua script on mmWaveStudio, and I was getting a 
```
&&&&&&&&&&&&&&&&&&&&
***Script FAILED!***
&&&&&&&&&&&&&&&&&&&&
Exception message is:
invalid arguments to method call
``` 
([mmWaveStudioLogWithOrginalLuaFile.txt](https://github.com/PreSenseRadar/OpenRadar/files/3986073/mmWaveStudioLogWithOrginalLuaFile.txt))
 because of line 88 on 1843_mmwavestudio_config.lua
`ar1.FrameConfig(START_CHIRP_TX, END_CHIRP_TX, NUM_FRAMES, CHIRP_LOOPS, PERIODICITY, 0, 1)`
I changed it to
`ar1.FrameConfig(START_CHIRP_TX, END_CHIRP_TX, NUM_FRAMES, CHIRP_LOOPS, PERIODICITY, 0, 0, 1)`
and mmWaveStudio outputs a ` ***Script completed successfully.*** ` message ([mmWaveStudioLogWithEditedLuaFile.txt](https://github.com/PreSenseRadar/OpenRadar/files/3986072/mmWaveStudioLogWithEditedLuaFile.txt)).

I am working with:
Hardware: AWR1843 and DCA1000
OS: Microsoft Windows 10 Home 
IDE: JetBrains PyCharm Community Edition 2019.2.4
Python: Python 3.8 (64-bit)
mmWave Studio: mmWave Studio 02.01.00.00

**Comment by jtang10** [comment]
Can you explain why you changed the last two parameters in the frameCfg from (0, 1) to (0, 0, 1). According to TI's document ([mmWave SDK User Guide](http://software-dl.ti.com/ra-processors/esd/MMWAVE-SDK/latest/exports/mmwave_sdk_user_guide.pdf)), the frameCfg only allows 7 parameters and the last two are usually fixed.

**Comment by TajVeerThiara** [comment]
Line 201 of `DataCaptureDemo_xWR.lua` in `C:\ti\mmwave_studio_02_01_00_00\mmWaveStudio\Scripts` is `ar1.FrameConfig(0, 0, 8, 128, 40, 0, 0, 1)` with 8 parameters, and the last three are (0, 0, 1).

**Comment by TajVeerThiara** [comment]
The relevant section in the mmWave SDK User Guide is for 3. 4. Configuration (.cfg) File Format not a .lua script. If you type `help ar1.FrameConfig()` in the Lua Shell in mmWave Studio, you will be returned the input parameter to the function. As seen from the screenshot below, there are 8 parameters.

![image](https://user-images.githubusercontent.com/25422461/73224966-fb0dd200-411f-11ea-96eb-c5977c21aaf6.png)

**Comment by edwin-pan** [comment]
It seems TI has added an extra parameter between when we pushed the original lua script and when @TajVeerThiara opened this issue. The correct command should have 8 parameters. ( #11 )

**Comment by edwin-pan** [comment]
Repo lua scripts now reflect change to accommodate TI's parameter update.
